### PR TITLE
fix angular is not defined error

### PR DESCRIPTION
**Pull request by physicsdude**

### CODE REVIEW

**Comment by feruzm** [comment]
@physicsdude in `bower-> ionic` folder I don't have ionic.bundle.js inside `js`.

Are you using ionicv2 ?

**Comment by physicsdude** [comment]
Not sure. Looks like your .js is under "releases". This is not really a big deal since it is a dev only issue but wanted to submit because others may have the same issue depending on their setup...

**Comment by physicsdude** [comment]
By the way I am not sure only because I'm not at the computer at this time :)

**Comment by feruzm** [comment]
you are right, I just checked and ionic changed their master to v2, before it was v1 so. I think only mentioning that in readme should fix the issue so that developers get ionic v1 via bower. Thanks ;)

**Pull request closed without merging**
